version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - '15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - '3366:3306'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - '8082:80'

volumes:
  rabbitmq: